### ISSUE TITLE
Runner unable to run again after OOM error

### ISSUE THREAD

**Issue by barrelltech** [phoenixframework/flame#66]
I'm testing some FLAME runners to do KMeans clustering. Trying to figure out how many embeddings I can do per fly.io machine size, so I'm testing a bunch of different values until failure.

When I use a value too high, the process crashes, the machine cleans up, and subsequent invocations of the runner error with:

```
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: the table identifier does not refer to an existing ETS table

    (stdlib 5.2.3) :ets.lookup_element(:kmeans_md, :meta, 2)
    (flame 0.5.1) lib/flame/pool.ex:381: FLAME.Pool.lookup_meta/1
    (flame 0.5.1) lib/flame/pool.ex:315: FLAME.Pool.caller_checkout!/5
    iex:1: (file)
```

I'm using these as `single_use: true` so I'm not super concerned about the OOM error. It's a pretty big issue that I cannot then run any more tasks with the runner though.

Not sure how to resolve the issue either - sometimes a restart fixes it, sometimes waiting 10+ minutes. Not a big issue for me, but seemed report-worthy!

**Comment by Lakret** [comment]
I have encountered the same issue and opened PR with a fix: https://github.com/phoenixframework/flame/pull/87. I would appreciate if somebody could check it out and happy to help with making it mergeable :)
